{% set name = "qarrayrun" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9627817b6ab706b183ccd589a2faaca018f139862f61664b87a70f4028fcc34

build:
  number: 0
  entry_points:
    - qarrayrun = qarrayrun.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python

test:
  imports:
    - qarrayrun
  commands:
    - qarrayrun --help
  requires:
    - pytest

about:
  home: https://github.com/CFSAN-Biostatistics/qarrayrun
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: A helper tool for running array jobs on an HPC computational node.

extra:
  recipe-maintainers:
    - dpryan79
