travis:
  secure:
    BINSTAR_TOKEN: FpSvr6EQcXNd41/A0HA8gN5VvSEtxJ7wjGhdGUajFQxd7yDJbYICLQMMYzr4QHlUmFp+tX729Lsr2N+E+Vzm3YU4oqGR2FUVf4zSu0UFygo6/zRVsn0FFZyUte/QJbFBbrBxeivbsu2CYgC/ji4QOL7Q2gFsShXvnTn1C55BxHETVlqvQmONG5zIBQPJFFqLwBih89BGxEKCS3DX38LFfI+ZKDz6CoWMntRIbs1ZYo59rT+voSEPzmBnPFrFLe9p2NOg0bp2q3/SU44sIQEvAup27FRYwFiESPu5vuxIwzx2frUxZ0T4zpGHp4AVr2W8ytCbNJQJc5LHa87hCd17ZPMZlJVBQ114GgX5mXMBy7sVcAq4/+4URiViB46taznBhTIegrCnM1netIqQPL885xnRCEqk/33UN+ynQLlv1RFNM1sw9d9vN6iEsdgaYKdL94HNxI0H6Mgfwygv2Aop2w/nOUoqW7NPFlL7nUQ5tr+QPDpVclhBsGs8ShuosDa/JheLxhBqaxXKUmpiuK7pFoTMIBpURl6OEsByiwCu/KCeiJ2mczJDOgkxTpa7HnhykxQd2EhisKY3ovEaF9dj/tkhXNh+iVReG+Crpzp26rV7zpNmcy06222uLMK6yu7LgnRxdlUePqISxHL6NrmAqpPbPgzlsey491/v4hTor14=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
